### ISSUE TITLE
Where we can get that company data?

### ISSUE THREAD

**Issue by srikanthNDM** [rajesh-gupta-14/LookAlike_Model_B2B_Customers_NLP#3]
characteristics include products developed, the technology stack, the size, the acquisitions and future goals of a company.

We can get size of the company but what about other data how we can get it?

And what is the outcome when u used this project in real time. What is the conversion ratio? thanks for the help.

**Comment by rajesh-gupta-14** [comment]
The way the search works is by querying Google with a certain set of keywords related to the characteristic for which we want data. For example, when we search for products developed by Amazon, an advanced google search looks somewhat like this: 'Amazon "products" "software" "properties"' etc. Then, the first n results are fetched from the Google search engine.

Thanks,
Rajesh.
________________________________
